---
title: "R Notebook"
output: html_notebook
---

**Generalized linear models**

**Practice Data Set:**

*Natural selection in song sparrows*

The song sparrow population on the island of Mandarte has been studied for many years by Jamie Smith, Peter Arcese, and collaborators. The birds were measured and banded and their fates on the island have recorded over many years. Here we will look for evidence of natural selection using the relationship between phenotypes and survival.

The data file, gives survival of young-of-the-year females over their first winter (1=survived, 0=died). The file includes measurements of beak and body dimensions: body mass (g), wing length, tarsus length, beak length, beak depth, beak width (all in mm), year of birth, and survival. These data were analyzed previously in D. Schluter and J. N. M Smith (1986, Evolution 40: 221-231).


Step 1: Read and examine the data
```{r}

```
  a. Read the data from the file and inspect the first few lines to make sure it was read correctly.
    
  b. You will compare survival probabilities among different years, so make sure that year is a categorical variable in your data frame.
    
  c. Plot survival against tarsus length of female sparrows. You may want to find a method to reduce the overlap of points (the response variable is 0 or 1) to see the patterns more clearly.
  
  d. Examine the plot. Can you visualize a trend? Use a smoothing method to see if any trend is present (most methods won’t constrain the curve to lie between 0 and 1, but at least you’ll get an idea of the pattern).


**Step 2: Fit a generalized linear model**

Note: Initially you can ignore the fact that the data are from multiple years. After you have finishe this exercise you can try adding it to see how it changes things

  e. The response variable is binary. What probability distribution is appropriate to describe the error distribution around a model fit? What is an appropriate link function?
  
  f. Fit a generalized linear model to the data on survival and tarsus length.
    
  g. Visualize the model fit (using ggplot or other graphics device).
    
  h. Obtain the estimated regression coefficients for the fitted model. What is the interpretation of these coefficients? On a piece paper (for your own knowledge not to be turned in) write down the complete formula for the model. 
  
   i. Use the coefficients to calculate the predicted survival probability of a song sparrow having tarsus length 20.5 mm*.
   
   j. Does the result agree with your plot of the fitted regression curve?
    
  k. The ratio (-intercept/slope) estimates the point at which probability of survival is changing most rapidly. In toxicology this point is known as the LD50. Calculate this value** and compare it visually (add a line or something) with the fitted curve. Does it agree?
  
  l. Finally, the slope of the curve at a given value for the explanatory variable x is b * p(x) * ( 1 - p(x) ) for a binomial response, where b is the slope coefficient of the fitted logistic regression model and p(x) is the predicted probability of survival at that x. 
  
  m. Calculate the likelihood-based 95% confidence interval for the logistic regression coefficients.
    
  n. The summary(z) output for the regression coefficients also includes “z values” and P-values. What caution would you take when interpreting these P-values? Use a more accurate method to test the null hypothesis of zero slope.


**Practice Data set 2**

**Crab satellites**

The horseshoe crab, Limulus polyphemus, has two alternative male reproductive morphs. Some males attach to females with a special appendage. The females bring these males with them when they crawl onto beaches to dig a nest and lay eggs, which the male then fertilizes. Other males are satellites, which are unattached to females but crowd around nesting pairs and obtain fertilizations. What attributes of a female horseshoe crab determine the number of satellite males she attracts on the beaches?

The data here provide measurements of 173 female horseshoe crabs and record the number of satellites she attracted. The data were gathered by Brockman (1996. Satellite male groups in horseshoe crabs, Limulus polyphemus. Ethology 102:1-21) and were published by Agresti (2002, Categorical data analysis, 2nd ed. Wiley). The variables are female color, spine condition, carapace width (cm), mass (kg), and number of satellite males.


**step 1. Read and examine the data**

  a. Read the data from the file. View the first few lines of data to make sure it was read correctly. Use the str command to see the variables and groups.
    
  b.Plot the number of satellites against the width of the carapace, a measure of female body size. Fit a smooth curve to examine the trend.


**step 2: Fit a generalized linear model**

  c. Fit a generalized linear model to the relationship between number of satellite males and female carapace width. What type of variable is the number of satellites? What probability distribution might be appropriate to describe the error distribution around a model fit? What is the appropriate link function? Fit hte model.

  d. Visualize the model fit on the transformed scale (coudl try to do it with visreg(z, xvar = "width.cm") and manually usign ggplot?), including confidence bands. This plot reminds us that on the transformed scale, glm() is fitting a straight line relationship. (Don’t worry about the points – they aren’t the transformed data, but rather are “working values” for the response variable from the last iteration of model fitting, which glm() uses behind the scenes to fit the model on the transformed scale.)


  c. Visualize the model fit on the original data scale. Note that is it curvilinear.
    
  d. Extract the estimated regression coefficients from your model object. What is the interpretation of these coefficients? On a piece of paper, write down the complete formula for your fitted model.
    
  e. Calculate the likelihood-based 95% confidence interval for the regression coefficients. The most useful estimate is that for the slope: exp(slope) represents the multiple to the response variable accompanying a 1-unit change in the explanatory variable. In other words, if the slope were found to be 1.2, this would indicate that a 1 cm increase in carapace width of a female is accompanied by a 1.2-fold increase in the number of male satellites.
    
  d. Test the null hypothesis of no relationship between number of satellite males and female carapace width. Notice how small the P-value is for the null hypothesis test for the slope. I’m afraid that this is a little optimistic. Why?
  
  e. When you extracted the regression coefficients from your model object, you probably saw the following line of output: “(Dispersion parameter for poisson family taken to be 1)”. Di you test this assumption of the model?  
    What are we really assuming* here?

  f. If you did not want to rely on this assumption (or you wanted to estimate the dispersion parameter), what option is available to you? Refit a generalized linear model without making the assumption that the dispersion parameter is 1.
    
  g. Extract and examine the coefficients of the new glm model object. Examine the estimated dispersion parameter. Is it close to 1? On this basis, which of the two glm fits to the same data would you regard as the more reliable? Can you test this with a quantiative method?
    
  h. How do the regression coefficients of this new fit compare with the estimates from the earlier model fit? How do the standard errors compare? If there are differences why?
  
  i. Visualize the new model fit and compare with the plot of the earlier fit. What difference do you notice?
  
  j. Redo the test of significance for the slope of the relationship between number of satellite mates and female carapace width. Remember if you chose to use a quasi distribution you have to use the F test rather than the likelihood ratio test in the anova command. How do the results compare with those from the previous fit?

